### Index page
http://localhost:3000

### Get financial news
http://localhost:3000/news

### Get today's disclosure
http://localhost:3000/disclosure

### Get ticker 
http://localhost:3000/ticker

### Get industry 
http://localhost:3000/industry

### Get individual field
http://localhost:3000/individual

### Get Chart Data 
POST http://localhost:3000/chart HTTP/1.1
content-type: application/json

{
	"symbol": "005930",
	"from": "20190101",
	"to": "20220101"
}